/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 101.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/101.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.19, -0.013]}>
        <mesh geometry={nodes.Head011.geometry} material={materials['Arch37_045_mat_1.001']} position={[0, 0.607, -1.144]} scale={[0.025, 0.08, 0.025]} />
      </group>
      <group position={[0, -0.117, 0.085]}>
        <mesh geometry={nodes.Head021.geometry} material={materials['Arch37_021_mat_1.001']} position={[0, 0.636, -0.992]} scale={0.025} />
      </group>
      <group position={[0, 0.01, 0]}>
        <mesh geometry={nodes.Head031.geometry} material={materials['Arch37_018_mat_3.001']} position={[0, 0.686, -1.153]} scale={0.025} />
        <mesh geometry={nodes.Head032.geometry} material={materials['Arch37_018_mat_1.001']} position={[0, 0.691, -1.218]} scale={0.025} />
      </group>
      <mesh geometry={nodes.Arch37_018_obj_1.geometry} material={materials['Arch37_018_mat_3.001']} position={[0, 0.191, 0]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_10.geometry} material={materials['Arch37_018_mat_3.001']} position={[-0.284, 0.554, -0.674]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_2.geometry} material={materials['Arch37_018_mat_4.001']} position={[0, 0.385, -0.485]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_3.geometry} material={materials['Arch37_018_mat_5.001']} position={[-0.002, 0.372, 0.28]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_4.geometry} material={materials['Arch37_018_mat_2.001']} position={[0.71, 0.079, 0.963]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_5.geometry} material={materials['Arch37_018_mat_2.001']} position={[-0.713, 0.079, 0.963]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_8.geometry} material={materials['Arch37_018_mat_4.001']} position={[0.383, 0.569, -0.88]} scale={0.025} />
      <mesh geometry={nodes.Arch37_018_obj_9.geometry} material={materials['Arch37_018_mat_4.001']} position={[-0.371, 0.581, -0.908]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/101.gltf')
